=== waudbylab/NMRLitmus/public/database/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "NMR Buffer Database Schema",
  "version": "0.2.0",
  "$defs": {
    "valueWithUncertainty": {
      "oneOf": [
        {
          "type": "number"
        },
        {
          "type": "array",
          "items": {
            "type": "number"
          },
          "minItems": 2,
          "maxItems": 2
        }
      ]
    }
  },
  "type": "object",
  "required": [
    "database_version",
    "samples",
    "buffers"
  ],
  "properties": {
    "database_version": {
      "type": "string"
    },
    "last_updated": {
      "type": "string",
      "format": "date"
    },
    "samples": {
      "type": "array",
      "description": "Sets of calibration samples",
      "items": {
        "type": "object",
        "required": [
          "sample_id",
          "solvent",
          "authors",
          "reference_temperature_K"
        ],
        "properties": {
          "sample_id": {
            "type": "string",
            "description": "unique sample ID, e.g. waudby_2025_d2o"
          },
          "solvent": {
            "type": "string",
            "enum": [
              "10% D2O",
              "100% D2O"
            ]
          },
          "authors": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "name",
                "affiliation",
                "email"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Author name"
                },
                "orcid": {
                  "type": "string",
                  "pattern": "^[0-9]{4}-[0-9]{4}-[0-9]{4}-[0-9]{3}[0-9X]$",
                  "description": "Author ORCID"
                },
                "affiliation": {
                  "type": "string",
                  "description": "Author affiliation"
                },
                "email": {
                  "type": "string",
                  "description": "Author email address"
                }
              }
            }
          },
          "date_measured": {
            "type": "string",
            "format": "date",
            "description": "Date of NMR measurements"
          },
          "reference_temperature_K": {
            "type": "number",
            "description": "Reference temperature (in K)"
          },
          "measurement_ranges": {
            "type": "object",
            "required": [
              "pH",
              "temperature_K",
              "ionic_strength_M"
            ],
            "properties": {
              "pH": {
                "type": "object",
                "required": [
                  "min",
                  "max"
                ],
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                },
                "description": "pH measurement range"
              },
              "temperature_K": {
                "type": "object",
                "required": [
                  "min",
                  "max"
                ],
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                },
                "description": "Range of measured temperatures (in K)"
              },
              "ionic_strength_M": {
                "type": "object",
                "required": [
                  "min",
                  "max"
                ],
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                },
                "description": "Range of ionic strengths (in M)"
              }
            },
            "description": "Range of measurement conditions (to warn of extrapolation)"
          },
          "temperature_calibration": {
            "type": "string",
            "description": "Description of temperature calibration method"
          },
          "pH_calibration": {
            "type": "string",
            "description": "Description of pH calibration method"
          },
          "ionic_strength_control": {
            "type": "string",
            "description": "Description of how ionic strength was controlled"
          },
          "reference_ionic_strength_M": {
            "type": "number",
            "description": "Reference ionic strength (in M)"
          }
        }
      }
    },
    "buffers": {
      "type": "array",
      "description": "List of calibrated buffers",
      "items": {
        "type": "object",
        "required": [
          "buffer_name",
          "sample_id",
          "ionisation_states",
          "pKa_parameters",
          "chemical_shifts"
        ],
        "properties": {
          "buffer_name": {
            "type": "string",
            "description": "Buffer name"
          },
          "smiles": {
            "type": "string",
            "description": "SMILES string for the buffer"
          },
          "sample_id": {
            "type": "string",
            "description": "Sample from which buffer calibration derives"
          },
          "version": {
            "type": "string",
            "description": "Version number (vX.Y.Z)"
          },
          "ionisation_states": {
            "type": "integer",
            "minimum": 1,
            "description": "Number of ionisation states (e.g. 2 for simple buffers)"
          },
          "pKa_parameters": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "pKa_index",
                "pKa"
              ],
              "properties": {
                "pKa_index": {
                  "type": "integer",
                  "minimum": 1,
                  "description": "One-based index of pKa"
                },
                "pKa": {
                  "$ref": "#/$defs/valueWithUncertainty",
                  "description": "pKa at reference temperature and ionic strength"
                },
                "ΔH_kJ_mol": {
                  "$ref": "#/$defs/valueWithUncertainty",
                  "description": "ΔH for temperature dependence"
                },
                "ΔCp_J_mol_K": {
                  "$ref": "#/$defs/valueWithUncertainty",
                  "description": "ΔCp for temperature dependence"
                },
                "protonated_charge": {
                  "type": "integer",
                  "description": "Charge of protonated state"
                },
                "ionic_strength_model": {
                  "type": "string",
                  "enum": [
                    "davies",
                    "none"
                  ]
                },
                "davies_prefactor": {
                  "$ref": "#/$defs/valueWithUncertainty",
                  "description": "constant C (pKa = pKa0 + C f(I))"
                }
              }
            },
            "description": "List of calibrated pKa values",
            "minItems": 1
          },
          "chemical_shifts": {
            "type": "object",
            "patternProperties": {
              "^(1H|13C|15N|19F|31P)$": {
                "type": "array",
                "items": {
                  "type": "object",
                  "required": [
                    "resonance_id",
                    "limiting_shifts"
                  ],
                  "properties": {
                    "resonance_id": {
                      "type": "string",
                      "description": "Unique to buffer, e.g. 'Ha'"
                    },
                    "description": {
                      "type": "string",
                      "description": "Assignment"
                    },
                    "multiplicity": {
                      "type": "string",
                      "enum": [
                        "singlet",
                        "doublet",
                        "triplet",
                        "quartet",
                        "multiplet"
                      ],
                      "description": "Peak multiplicity"
                    },
                    "limiting_shifts": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "required": [
                          "ionisation_state",
                          "shift_ppm"
                        ],
                        "properties": {
                          "ionisation_state": {
                            "type": "integer",
                            "minimum": 0,
                            "description": "Zero-based index (from most protonated)"
                          },
                          "shift_ppm": {
                            "$ref": "#/$defs/valueWithUncertainty",
                            "description": "Chemical shift at reference temperature and ionic strength"
                          },
                          "temperature_coefficient_ppm_per_K": {
                            "$ref": "#/$defs/valueWithUncertainty",
                            "description": "dδ/dT (in ppm / K)"
                          },
                          "ionic_strength_coefficient_ppm_per_M": {
                            "$ref": "#/$defs/valueWithUncertainty",
                            "description": "dδ/dI (in ppm / M)"
                          }
                        }
                      },
                      "description": "Limiting chemical shifts"
                    }
                  }
                },
                "description": "Nucleus",
                "minItems": 1
              }
            },
            "description": "Buffer chemical shifts",
            "properties": {}
          },
          "notes": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== waudbylab/NMRLitmus/public/database/database.json
{
  "$schema": "schema.json",
  "database_version": "0.0.3",
  "last_updated": "2026-06-06",
  "samples": [
    {
      "sample_id": "valerie_group1_h2o",
      "solvent": "10% D2O",
      "authors": [
        {
          "name": "Chris Waudby",
          "email": "c.waudby@ucl.ac.uk",
          "orcid": "0000-0001-7810-3753",
          "affiliation": "UCL School of Pharmacy"
        }
      ],
      "date_measured": "2025-11-28",
      "reference_temperature_K": 298.0,
      "reference_ionic_strength_M": 0.0,
      "measurement_ranges": {
        "pH": {
          "min": 3.4,
          "max": 10.0
        },
        "temperature_K": {
          "min": 283,
          "max": 310
        },
        "ionic_strength_M": {
          "min": 0.0,
          "max": 0.3
        }
      },
      "temperature_calibration": "d4-methanol chemical shift thermometer",
      "pH_calibration": "Hanna HI-2002 Edge pH Meter, calibrated against NIST-traceable buffers pH 4.01, 7.00, 10.01, thermostatted at 298 K",
      "ionic_strength_control": "Addition of 0, 150 or 300 mM NaCl"
    }
  ],
  "buffers": [
    {
      "buffer_name": "Imidazole",
      "smiles": "C1=CN=CN1",
      "sample_id": "valerie_group1_h2o",
      "ionisation_states": 2,
      "pKa_parameters": [
        {
          "pKa_index": 1,
          "pKa": [
            7.1822,
            0.0089
          ],
          "ΔH_kJ_mol": [
            -11.1434,
            0.2205
          ],
          "protonated_charge": 1,
          "davies_prefactor": [
            0.1207,
            0.0304
          ]
        }
      ],
      "chemical_shifts": {
        "1H": [
          {
            "resonance_id": "Ha",
            "description": "",
            "multiplicity": "singlet",
            "limiting_shifts": [
              {
                "ionisation_state": 0,
                "shift_ppm": [
                  8.66947,
                  0.00159
                ],
                "temperature_coefficient_ppm_per_K": [
                  -0.00047,
                  0.00008
                ],
                "ionic_strength_coefficient_ppm_per_M": [
                  0.03146,
                  0.00758
                ]
              },
              {
                "ionisation_state": 1,
                "shift_ppm": [
                  7.76789,
                  0.00196
                ],
                "temperature_coefficient_ppm_per_K": [
                  0.00102,
                  0.00011
                ],
                "ionic_strength_coefficient_ppm_per_M": [
                  0.02361,
                  0.00936
                ]
              }
            ]
          },
          {
            "resonance_id": "Hb",
            "description": "",
            "multiplicity": "singlet",
            "limiting_shifts": [
              {
                "ionisation_state": 0,
                "shift_ppm": [
                  7.46761,
                  0.00149
                ],
                "temperature_coefficient_ppm_per_K": [
                  0.00032,
                  0.00008
                ],
                "ionic_strength_coefficient_ppm_per_M": [
                  0.02360,
                  0.00707
                ]
              },
              {
                "ionisation_state": 1,
                "shift_ppm": [
                  7.12636,
                  0.00176
                ],
                "temperature_coefficient_ppm_per_K": [
                  0.00078,
                  0.00009
                ],
                "ionic_strength_coefficient_ppm_per_M": [
                  0.01593,
                  0.00843
                ]
              }
            ]
          }
        ]
      },
      "notes": "Testing - not final dataset."
    }
  ]
}
